yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]


"""Добавить в гитигнор это
# папки со статикой и медиа
static/
yatube/posts/static/
yatube/media/"""

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']

        if data.lower() == "":
            raise forms.ValidationError('А кто форму будет заполнять?')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        data = self.cleaned_data['text']

        if data.lower() == "":
            raise forms.ValidationError('Ну хоть что-то напиши')
        return data

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User, Comment, Follow
from . import consts, utils
from .forms import PostForm, CommentForm
from django.urls import reverse


def index(request):
    """Вызывает шаблон главной страницы сайта.
    Кеширование выполнено способом -
    в коде шаблона."""
    post_list = Post.objects.all()

    page_obj = utils.make_paginator(
        post_list,
        request,
        consts.QUANTITY_OF_POST_TEN
    )

    context = {
        'page_obj': page_obj,
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    """Обрабатывает шаблон для страницы группы."""
    group = get_object_or_404(Group, slug=slug)

    post_list = group.posts.all()
    page_obj = utils.make_paginator(
        post_list,
        request,
        consts.QUANTITY_OF_POST_TEN
    )

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Профайл пользователя."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()

    page_obj = utils.make_paginator(
        post_list,
        request,
        consts.QUANTITY_OF_POST_TEN
    )
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    else:
        following = False
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    template = 'posts/profile.html'
    return render(request, template, context)


def post_detail(request, post_id):
    """Страница поста."""
    post = Post.objects.get(id=post_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    template = 'posts/post_detail.html'
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None
    )
    if form.is_valid():
        temp_form = form.save(commit=False)
        temp_form.author = request.user
        temp_form.save()
        return redirect('posts:profile', temp_form.author)
    context = {
        'form': form,
    }
    return render(request, template, context)


def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(
        request,
        template,
        {'form': form, 'is_edit': True, 'post': post}
    )


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = utils.make_paginator(
        post_list,
        request,
        consts.QUANTITY_OF_POST_TEN
    )
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} 
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}       
              Новый пост
            {% endif %}             
          </div>
          {% if form.errors %}
            {% for field in form %} 
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %} 
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                  <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                    >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                    Сохранить
                {% else %}
                    Добавить
                {% endif %}
              </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load cache %}
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    <title>
      {% block title %}
        Подписки
      {% endblock %}
    </title>  
  </head>
  <body>
    {% block content %}
      {% include 'posts/includes/switcher.html' %}
      {% cache 20 follow_index_page%}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1> Это главная страница сайта </h1>
        {% for post in page_obj %}
          {% block post_card %}
            {% include 'includes/post_card.html' %}
          {% endblock %}
          <!--Условие для предоставление верной ссылки-->
          {% if post.group %}
            <a 
            href = "{% url 'posts:group_list' post.group.slug %}"> 
            Все все записи группы
            </a>
          {% endif %}
             / 
            <a
            href = "{% url 'posts:profile' post.author.username %}">
            Профайл пользователя
            </a>
          {% if not forloop.last %}<hr>{% endif %} 
        {% endfor %}
      </div>
      {% include 'posts/includes/paginator.html' %}
      {% endcache %}
    {% endblock %}      
  </body>
</html>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    <title>
      {% block title %}
         {{ group }}
      {% endblock %}
    </title>
  </head> 
  <body>
    <header>      
    </header>
    <main>
      {% block header %} {{group}} {% endblock %}
      {% block content %}
        <!-- класс py-5 создает отступы сверху и снизу блока -->
        <div class="container py-5">
          <h1> Записи сообщества: {{ group }}</h1>
          <p> {{ group.description }} </p>
          {% for post in page_obj %}
            {% block post_card %}
              {% include 'includes/post_card.html'%}
            {% endblock %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
        </div>
        <a href="{% url 'posts:index' %}" >Back to the choppa</a>
      {% include 'posts/includes/paginator.html' %}
      {% endblock %} 
    </main>
    {% block footer %}
      <footer class="page-footer font-small blue border-top">
        <div class="footer-copyright text-center py-3">© 2022 Copyright 
          <p><span style="color:red">Ya</span>tube</p> 
        </div>    
      </footer>
    {% endblock %}
  </body>
</html> 

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load cache %}
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    <title>
      {% block title %}
        Последние обновления на сайте
      {% endblock %}
    </title>  
  </head>
  <body>
    {% block content %}
      {% include 'posts/includes/switcher.html' %}
      {% cache 20 index_page%}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1> Это главная страница сайта </h1>
        {% for post in page_obj %}
          {% block post_card %}
            {% include 'includes/post_card.html' %}
          {% endblock %}
          <!--Условие для предоставление верной ссылки-->
          {% if post.group %}
            <a 
            href = "{% url 'posts:group_list' post.group.slug %}"> 
            Все все записи группы
            </a>
          {% endif %}
             / 
            <a
            href = "{% url 'posts:profile' post.author.username %}">
            Профайл пользователя
            </a>
          {% if not forloop.last %}<hr>{% endif %} 
        {% endfor %}
      </div>
      {% include 'posts/includes/paginator.html' %}
      {% endcache %}
    {% endblock %}      
  </body>
</html>

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% load static %}
<html lang="ru">
  <head>
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    <title>{% block title%} Пост {{ post.text|truncatechars:30 }} {% endblock%} </title>
  </head>
  <body>
    {% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
              <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{post.author.posts.count}}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %} 
        </article>
      </div>
    </main>
    {% endblock %}
  </body>
</html>

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="ru"> 
  <head>  
    <!-- Подключены иконки, стили и заполенены мета теги -->
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img\fav\fav.ico" type="image'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img\fav\apple-touch-icon.png' %}">
    <link rel="icon" type="image\png" sizes="32x32" href="{% static 'img\fav\favicon-32x32.png'%}">
    <link rel="icon" type="image\png" sizes="16x16" href="{% static 'img\fav\favicon-16x16.png'%}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
    <title>Профайл пользователя {{ author.get_full_name }}</title>
  </head>
  <body>       
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="/">
            <img src="/static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>      
    </header>
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{author.posts.count}} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        {% for post in page_obj %}
          <article>
            {% include 'includes/post_card.html' %}
          </article>
          {% if post.group %}       
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}       
          <hr>
        {% endfor %}
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->
        {% include 'posts/includes/paginator.html' %}  
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html> 